openapi: 3.0.3
info:
  title: OCPP Central System 1.6 API
  description: |-
    OCPP1.6 central system API 
 
  # termsOfService: http://swagger.io/terms/
  # contact:
  #   email: apiteam@swagger.io
  # license:
  #   name: Apache 2.0
  #   url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
# externalDocs:
#   description: Find out more about Swagger
#   url: http://swagger.io
servers:
  - url: http://34.94.253.188:3021
  - url: http://localhost:3021
# tags:
#   - name: api
#     description: Everything about your Pets
#     externalDocs:
#       description: Find out more
#       url: http://swagger.io
paths:
  /api/call:
    post:
      tags:
        - api
      summary: Call any charger method 
      description: Add a new pet to the store
      operationId: Call
      requestBody:
        description: Create a new pet in the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Payload'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
        '400':
          description: Invalid input
        '422':
          description: Validation exception
  /api/chager-list:
    get:
      tags:
        - api
      summary: SSE subsribe charger list
      description: Multiple status values can be provided with comma separated strings
      operationId: findPetsByStatus
      parameters:
        - name: status
          in: query
          description: Status values that need to be considered for filter
          required: false
          explode: true
          schema:
            type: string
            default: available
            enum:
              - available
              - pending
              - sold
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Response'          
        '400':
          description: Invalid status value
  /api/events:
    get:
      tags:
        - api
      summary: SSE subsribe events
      description: Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
      operationId: findPetsByTags
      parameters:
        - name: tags
          in: query
          description: Tags to filter by
          required: false
          explode: true
          schema:
            type: array
            items:
              type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Response'          
        '400':
          description: Invalid tag value
components:
  schemas:
    Params:
      type: object
      properties:
        connectorId:
          type: integer
          format: int64
          example: 1
        idTag:
          type: string
          example: user#10
      xml:
        name: category
    Payload:
      required:
        - name
        - photoUrls
      type: object
      properties:
        chargePointId:
          type: string
          example: CP01
        method:
          type: string
          example: RemoteStartTransaction  
        params:
          $ref: '#/components/schemas/Params'
    Response:
      required:
        - name
        - photoUrls
      type: object
      properties:
        data:
          type: object
          example: {}
    
    